services:
  db:
    image: postgres:latest
    container_name: postgres_container-1
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spider:
    build: .
    container_name: spider_container-1
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://your_username:your_password@postgres:5432/your_database"
    command: ["scrapy", "crawl", "trip_spider"]

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container-1
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin       
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
